const mockMaterials = [
    {
        id: 'WL-00001',
        materialName: '20%草铵膦水剂',
        commonName: '草铵膦',
        baseUnit: '升',
        specModel: '5L/桶',
        materialLevel: '一级',
        dosageForm: '水剂',
        cropSite: '果园、非耕地',
        controlTarget: '牛筋草、狗尾草、马唐等一年生杂草',
        usageTime: '杂草3-5叶期',
        registrationNo: 'PD20200012',
        productAttribute: '除草剂',
        cropAttribute: '大田作物',
        productManager: '张伟',
        productInfo: '本产品为触杀型除草剂，对多种一年生和多年生杂草有良好防效。施药后6小时遇雨不影响药效。'
    },
    {
        id: 'WL-00002',
        materialName: '40%多菌灵悬浮剂',
        commonName: '多菌灵',
        baseUnit: '千克',
        specModel: '1kg/袋',
        materialLevel: '一级',
        dosageForm: '悬浮剂',
        cropSite: '蔬菜、果树、水稻',
        controlTarget: '稻瘟病、纹枯病、白粉病、炭疽病',
        usageTime: '发病初期',
        registrationNo: 'PD20180345',
        productAttribute: '杀菌剂',
        cropAttribute: '经济作物',
        productManager: '李娜',
        productInfo: '广谱性杀菌剂，具有保护和治疗作用。可用于防治多种作物的真菌性病害。'
    },
    {
        id: 'WL-00003',
        materialName: '25%吡虫啉可湿性粉剂',
        commonName: '吡虫啉',
        baseUnit: '克',
        specModel: '100g/袋',
        materialLevel: '二级',
        dosageForm: '可湿性粉剂',
        cropSite: '小麦、水稻、蔬菜、果树',
        controlTarget: '蚜虫、飞虱、蓟马、粉虱等刺吸式口器害虫',
        usageTime: '害虫发生初期',
        registrationNo: 'PD20190789',
        productAttribute: '杀虫剂',
        cropAttribute: '大田作物',
        productManager: '王强',
        productInfo: '烟碱类杀虫剂，具有内吸、触杀和胃毒作用。对刺吸式口器害虫有特效，持效期长。'
    },
    {
        id: 'WL-00004',
        materialName: '5%阿维菌素乳油',
        commonName: '阿维菌素',
        baseUnit: '毫升',
        specModel: '500ml/瓶',
        materialLevel: '二级',
        dosageForm: '乳油',
        cropSite: '蔬菜、果树、棉花',
        controlTarget: '红蜘蛛、斑潜蝇、菜青虫、棉铃虫',
        usageTime: '低龄幼虫期',
        registrationNo: 'PD20170567',
        productAttribute: '杀虫剂',
        cropAttribute: '经济作物',
        productManager: '陈芳',
        productInfo: '生物源杀虫剂，具有触杀和胃毒作用。对螨类和鳞翅目幼虫有良好防效。'
    },
    {
        id: 'WL-00005',
        materialName: '95%草甘膦原药',
        commonName: '草甘膦',
        baseUnit: '千克',
        specModel: '25kg/袋',
        materialLevel: '三级',
        dosageForm: '原药',
        cropSite: '非耕地、果园行间',
        controlTarget: '一年生及多年生杂草',
        usageTime: '杂草生长旺盛期',
        registrationNo: 'PD20150234',
        productAttribute: '除草剂',
        cropAttribute: '非耕地',
        productManager: '刘洋',
        productInfo: '广谱灭生性除草剂，通过植物茎叶吸收后传导至根部。用于非耕地除草效果显著。'
    },
    {
        id: 'WL-00006',
        materialName: '15%氟磺胺草醚乳油',
        commonName: '氟磺胺草醚',
        baseUnit: '升',
        specModel: '1L/瓶',
        materialLevel: '二级',
        dosageForm: '乳油',
        cropSite: '大豆田、花生田',
        controlTarget: '反枝苋、马齿苋、藜等阔叶杂草',
        usageTime: '大豆2-4片复叶期',
        registrationNo: 'PD20210456',
        productAttribute: '除草剂',
        cropAttribute: '豆科作物',
        productManager: '赵敏',
        productInfo: '二苯醚类选择性苗后除草剂，用于大豆和花生田防除阔叶杂草。'
    },
    {
        id: 'WL-00007',
        materialName: '80%代森锰锌可湿性粉剂',
        commonName: '代森锰锌',
        baseUnit: '千克',
        specModel: '2kg/袋',
        materialLevel: '一级',
        dosageForm: '可湿性粉剂',
        cropSite: '果树、蔬菜、大田作物',
        controlTarget: '霜霉病、疫病、炭疽病、叶斑病',
        usageTime: '发病前或发病初期',
        registrationNo: 'PD20160890',
        productAttribute: '杀菌剂',
        cropAttribute: '经济作物',
        productManager: '张伟',
        productInfo: '广谱保护性杀菌剂，含锰、锌微量元素。能有效防治多种真菌性病害。'
    },
    {
        id: 'WL-00008',
        materialName: '20%噻虫嗪水分散粒剂',
        commonName: '噻虫嗪',
        baseUnit: '克',
        specModel: '200g/袋',
        materialLevel: '二级',
        dosageForm: '水分散粒剂',
        cropSite: '水稻、小麦、棉花、蔬菜',
        controlTarget: '稻飞虱、蚜虫、蓟马、白粉虱',
        usageTime: '害虫发生初期',
        registrationNo: 'PD20200678',
        productAttribute: '杀虫剂',
        cropAttribute: '大田作物',
        productManager: '李娜',
        productInfo: '新一代烟碱类杀虫剂，具有胃毒、触杀和内吸活性。杀虫谱广、活性高、持效期长。'
    },
    {
        id: 'WL-00009',
        materialName: '30%苯醚甲环唑水分散粒剂',
        commonName: '苯醚甲环唑',
        baseUnit: '克',
        specModel: '100g/袋',
        materialLevel: '一级',
        dosageForm: '水分散粒剂',
        cropSite: '果树、蔬菜、禾谷类作物',
        controlTarget: '黑星病、白粉病、叶斑病、锈病',
        usageTime: '发病初期',
        registrationNo: 'PD20190123',
        productAttribute: '杀菌剂',
        cropAttribute: '经济作物',
        productManager: '王强',
        productInfo: '三唑类广谱杀菌剂，具有保护、治疗和铲除作用。对子囊菌、担子菌和半知菌引起的病害有特效。'
    },
    {
        id: 'WL-00010',
        materialName: '10%氰氟草酯乳油',
        commonName: '氰氟草酯',
        baseUnit: '升',
        specModel: '1L/瓶',
        materialLevel: '三级',
        dosageForm: '乳油',
        cropSite: '水稻田',
        controlTarget: '稗草、千金子等禾本科杂草',
        usageTime: '水稻插秧后5-7天',
        registrationNo: 'PD20180456',
        productAttribute: '除草剂',
        cropAttribute: '水稻',
        productManager: '陈芳',
        productInfo: '芳氧苯氧丙酸酯类除草剂，用于水稻田防除禾本科杂草。对千金子、稗草特效。'
    },
    {
        id: 'WL-00011',
        materialName: '45%咪鲜胺水乳剂',
        commonName: '咪鲜胺',
        baseUnit: '毫升',
        specModel: '500ml/瓶',
        materialLevel: '一级',
        dosageForm: '水乳剂',
        cropSite: '果树、蔬菜、食用菌',
        controlTarget: '炭疽病、蒂腐病、青霉病、绿霉病',
        usageTime: '发病初期或采后处理',
        registrationNo: 'PD20210234',
        productAttribute: '杀菌剂',
        cropAttribute: '经济作物',
        productManager: '刘洋',
        productInfo: '咪唑类广谱杀菌剂，对多种作物由子囊菌和半知菌引起的病害有明显防效。也可用于水果采后防腐保鲜。'
    },
    {
        id: 'WL-00012',
        materialName: '50%氯氰菊酯乳油',
        commonName: '氯氰菊酯',
        baseUnit: '毫升',
        specModel: '250ml/瓶',
        materialLevel: '二级',
        dosageForm: '乳油',
        cropSite: '蔬菜、果树、棉花、大豆',
        controlTarget: '菜青虫、棉铃虫、食心虫、蚜虫',
        usageTime: '低龄幼虫期',
        registrationNo: 'PD20170890',
        productAttribute: '杀虫剂',
        cropAttribute: '大田作物',
        productManager: '赵敏',
        productInfo: '拟除虫菊酯类杀虫剂，具有触杀和胃毒作用。杀虫谱广，击倒速度快。'
    }
];
